[package]
name = "emulot"
version = "1.0.0"
description = "A configuration management solution for QEMU"
edition = "2021"
authors = ["Jeff Caffrey-Hill <jeff@caffreyhill.com>"]
license = "MIT"
repository = "https://github.com/ReverentEngineer/emulot"
readme = "README.md"
keywords = ["emulation", "management", "QEMU"]

[dependencies]
axum = { version = "0.6.10", features = ["macros"] }
chashmap = "2.2.2"
clap = { version = "4.1.8", features = ["derive"] }
pin-project-lite = "0.2.9"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.94"
serde_yaml = "0.9.17"
tokio = { version = "1.26.0", features = ["rt", "macros", "process", "io-util"] }
