name: Cargo Build & Test

on:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test with ${{ matrix.toolchain }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: sudo apt install -y qemu pkg-config libssl-dev libsqlite3-dev qemu-system-x86
        if: matrix.os == 'ubuntu-latest'
      - run: brew install qemu pkg-config openssl sqlite3
        if: matrix.os == 'macos-latest'
      - run: cargo build --verbose
      - run: cargo test --verbose
